# Generated by Django 5.2.7 on 2025-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('shop_id', models.CharField(max_length=20, unique=True)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='distributors/')),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('area_assigned', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
