# Generated by Django 5.2.7 on 2025-11-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_from', models.DateField(blank=True, null=True)),
                ('distribution_to', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('slot_limit', models.IntegerField(default=0)),
                ('biometric_status', models.CharField(default='ACTIVE', max_length=10)),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
    ]
