# Generated by Django 5.2.7 on 2025-11-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_announcement_distributorsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
