# Generated by Django 5.2.7 on 2025-10-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='distributor_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_id',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
