# Generated by Django 5.2.7 on 2025-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_distributor_id_customuser_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shop_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
